apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rook-ceph
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/TimJones/home-cluster.git
  destinations:
  - server: https://kubernetes.default.svc
    namespace: rook-ceph
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
