apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.0.1
- github.com/argoproj-labs/applicationset/manifests/namespace-install?ref=v0.1.0
- master-set.yaml
- ./projects

patches:
- custom-tooling.yaml
