apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: master-set
spec:
  generators:
  - git:
      repoURL: https://github.com/TimJones/home-cluster.git
      revision: HEAD
      directories:
      - path: apps/*
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: '{{ path.basename }}'
      source:
        repoURL: https://github.com/TimJones/home-cluster.git
        targetRevision: HEAD
        path: '{{ path }}'
        kustomize:
          version: v4.1.3
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ path.basename }}'
